/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--color-primary)',
          50:  '#eff6ff',
          100: '#dbeafe',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          900: '#1e3a8a',
        },
        accent: 'var(--color-accent)',
        success: 'var(--color-success)',
        danger:  'var(--color-danger)',
        warning: 'var(--color-warning)',
        sidebar: 'var(--color-sidebar)',
        // Material 3 design tokens mapping
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-error": "var(--color-on-error)",
        "primary-fixed": "var(--color-primary-fixed)",
        "primary-container": "var(--color-primary-container)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-error-container": "var(--color-on-error-container)",
        "surface-tint": "var(--color-surface-tint)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-background": "var(--color-on-background)",
        "secondary": "var(--color-secondary)",
        "background": "var(--color-background)",
        "secondary-container": "var(--color-secondary-container)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-primary": "var(--color-on-primary)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "tertiary": "var(--color-tertiary)",
        "inverse-surface": "var(--color-inverse-surface)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "surface": "var(--color-surface)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-secondary": "var(--color-on-secondary)",
        "surface-container-low": "var(--color-surface-container-low)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "outline": "var(--color-outline)",
        "on-tertiary": "var(--color-on-tertiary)",
        "error": "var(--color-error)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "error-container": "var(--color-error-container)",
        "outline-variant": "var(--color-outline-variant)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "surface-container": "var(--color-surface-container)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-surface": "var(--color-on-surface)",
        "surface-variant": "var(--color-surface-variant)",
        "inverse-primary": "var(--color-inverse-primary)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "4px",
        "container-margin": "32px",
        "xs": "4px",
        "md": "16px",
        "2xl": "48px",
        "gutter": "24px",
        "xl": "32px",
        "sm": "8px",
        "lg": "24px"
      },
      fontFamily: {
        "headline-sm": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "headline-xl": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
